package ch.bissbert.bissblog.data;

import lombok.*;
import org.hibernate.Hibernate;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Objects;

@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name = "images")
/**
 * Represents an image in the database with a unique id and a description.
 *
 * It is used to store the images of the blog posts.
 * @author Bissbert
 * @version 1.0.0
 * @since 1.0.0
 * @see ch.bissbert.bissblog.data.BlogPost
 */
public class Image {

    /**
     * The unique id of the image.
     * Automatically generated by hibernate.
     */
    @Id
    @GeneratedValue
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    @Column(name = "id", updatable = false, nullable = false)
    private String id;

    /**
     * The data of the image in a byte array.
     */
    @Lob
    private byte[] data;

    /**
     * mimetype of the image.
     */
    private String mimeType;

    /**
     * The description of the image.
     */
    private String description;

    /**
     * The blog post the image belongs to.
     */
    @ManyToOne
    @JoinColumn(name = "post_id")
    private BlogPost blogPost;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
        Image image = (Image) o;
        return Objects.equals(id, image.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
